[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Misc Fixed"
style = "Bold"

[font.bold_italic]
family = "Misc Fixed"
style = "Bold"

[font.italic]
family = "Misc Fixed"
style = "Bold"

[font.normal]
family = "Misc Fixed"
style = "Bold"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[general]
import = ["/home/stephen/git/stephen/comet64/alacritty/comet64.toml"]

[terminal.shell]
program = "tmux"
